apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  type: NodePort  # Change from ClusterIP to NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Container's exposed port
      nodePort: 30008   # Specify a port between 30000-32767
